### ISSUE TITLE
Type 'com.github.ksoichiro.console.reporter.ReportCoverageTask' property 'extension' is missing an input or output annotation

### ISSUE THREAD

**Issue by abedurftig** [ksoichiro/gradle-console-reporter#15]
I am trying to run the console reporter on Jacoco coverage reports using Gradle 7.0.2

```
> Task :reportCoverage FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':reportCoverage' (type 'ReportCoverageTask').
  - Type 'com.github.ksoichiro.console.reporter.ReportCoverageTask' property 'extension' is missing an input or output annotation.

    Reason: A property without annotation isn't considered during up-to-date checking.

    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

    Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#missing_annotation for more details about this problem.
```

**Comment by josephShield** [comment]
I am having this exact issue breaking my build with Gradle 7.0.1

**Comment by bradleyrgriffin** [comment]
Having the same issue w/ Gradle 7.1.1; and plugin version:
id 'com.github.ksoichiro.console.reporter' version '0.6.2'

**Comment by edoswaldgo** [comment]
Good day @ksoichiro , @sleberrigaud !

I created a pull request [here](https://github.com/ksoichiro/gradle-console-reporter/pull/16) for Gradle 7.x support. Kindly help review the change.

Thank you!

**Comment by marcellodesales** [comment]
> Good day @ksoichiro , @sleberrigaud !
> 
> I created a pull request [here](https://github.com/ksoichiro/gradle-console-reporter/pull/16) for Gradle 7.x support. Kindly help review the change.
> 
> Thank you!

It would be great to have it resolved ASAP...

@edoswalgo is there a workaround while the PR is on a flight?

**Comment by ksoichiro** [comment]
Hi everyone! Sorry for my very late reply and inconvenience.
I'll check!

**Comment by ksoichiro** [comment]
I merged https://github.com/ksoichiro/gradle-console-reporter/pull/16 and released v0.6.3. Thank you!

It's already available in Gradle plugin portal.
https://plugins.gradle.org/plugin/com.github.ksoichiro.console.reporter
It seems it's not available in Maven Central Repository yet, but I think it will soon be available.
https://search.maven.org/artifact/com.github.ksoichiro/gradle-console-reporter

**Comment by marcellodesales** [comment]
@ksoichiro it worked!!! Thank you!

**Comment by edoswaldgo** [comment]
That's great! Thank you very much @ksoichiro , @marcellodesales !

**Comment by abedurftig** [comment]
Thanks everyone! I will close the issue then.
